name: Django CI

on:
  push:
    branches: [main, deploy]
  pull_request:
    branches: [main, deploy]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8.8]

    steps:
      - uses: actions/checkout@v2
      - name: psycopg2 prerequisites
        run: sudo apt-get install libpq-dev
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies

        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - uses: harmon758/postgresql-action@v1
        with:
          postgresql version: "13.2"
      - name: Run migrations
        run: python manage.py migrate
        env: # Or as an environment variable
          SECRET_KEY_DJANGO_BANK: ${{ secrets.SECRET_KEY_DJANGO_BANK}}
          MAIL_VERIFY_PASSWORD: ${{secrets.MAIL_VERIFY_PASSWORD}}
          MODE_DJANGO_BANK: ${{secrets.MODE_DJANGO_BANK}}
          MAIL_VERIFY_EMAIL: ${{secrets.MAIL_VERIFY_EMAIL}}
      - name: Running Tests
        env:
          SECRET_KEY_DJANGO_BANK: ${{ secrets.SECRET_KEY_DJANGO_BANK}}
          MAIL_VERIFY_PASSWORD: ${{secrets.MAIL_VERIFY_PASSWORD}}
          MODE_DJANGO_BANK: ${{secrets.MODE_DJANGO_BANK}}
          MAIL_VERIFY_EMAIL: ${{secrets.MAIL_VERIFY_EMAIL}}
        run: |
          python manage.py test
